### ISSUE TITLE
adns module raises segmentation fault upon initialisation

### ISSUE THREAD

**Issue by PLPeeters** [pyston/pyston_v2#92] opened 2021-09-15 10:32 UTC
I'm using the [adns](https://pypi.org/project/adns/) module in a project that I migrated to Pyston with great performance improvements, but the adns module seems to be the only one that does not want to work, raising a segmentation fault upon initialisation:

```
Python 3.8.8 (heads/2.3_release:4b9a88fc50, Jul  8 2021, 15:46:12)
[Pyston 2.3.0, GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adns
created module adns Sep 15 2021 12:21:29
>>> resolver = adns.init()
Segmentation fault
```

Pyston and adns were installed in a fresh `ubuntu:20.04` Docker container as follows:

```
apt-get update
apt-get install -y curl
curl -Lo /tmp/pyston.deb https://github.com/pyston/pyston/releases/download/v2.3/pyston_2.3_20.04.deb
apt-get update
apt-get install --no-install-recommends -y libadns1-dev gcc /tmp/pyston.deb
pyston -m pip install adns==1.4-py0
```

**Comment by undingen** [comment] 2021-09-15 11:40
Thanks for the detailed bug report!
I could reproduce the issue. It seems that `adns_init()` is failing and afterwards it calls `adns_finish()` to clean up and segfaults.
I'm not sure why `adns_init()` is failling... if I install e.g. `apt-get install netbase` its working afterwards... (but it's not specific to this package some different ones also make it work while some don't)?!?

**Comment by PLPeeters** [comment] 2021-09-15 12:03
@undingen Thanks for the feedback, that's interesting.

I just figured out that installing the latest version from GitHub while forcing it to recompile works:

```
pyston -m pip install git+https://github.com/trolldbois/python3-adns --no-binary adns
```

Not sure if this warrants a close or if this is still worthy of further investigation given it just works using standard Python?

**Comment by undingen** [comment] 2021-09-15 12:52
I finished debugging the issue:
It's caused if the file  `/etc/protocols` is missing. Installing it via `netbase` or by manually creating/copying the file fixes the problem.
Therefore I think it's not a pyston problem but instead I think `libadns1` should depend on `netbase` if it requires it.

I will close this because I'm quite sure cpython would run into the same issue if build from scratch without installing netbase.

BTW: if you can talk about it: how large of a perf improvment are you seeing using pyston and what kind of workload is it (webserver? etc)? Always interested in hearing about use cases of pyston :)

**Comment by PLPeeters** [comment] 2021-09-15 13:14
@undingen That was quick! I just checked and `/etc/protocols` is indeed created as well after running the install from GitHub with the `--no-binary` option above.

Regarding performance, all else being equal, we're seeing an ~18% reduction of processing time for our crawlers, which use Tornado, as well as a ~29% reduction in processing time for the application of an AdaBoost classifier. It's honestly incredible to get such a boost just by switching to Pyston :)

**Closed as completed** 2021-09-15 13:30 UTC
