### ISSUE TITLE
In order to install cryptography I needed to install rust in WSL2 with Ubuntu 20.04

### ISSUE THREAD

**Issue by calvma** [pyston/pyston_v2#38] opened 2021-05-21 19:50 UTC
I'm using the latest .deb release file with WSL2 and Ubuntu 20.04 in windows 10 Pro

I got an error that said that upgrading pip would fix the issue, because apparently the newest version of pip can install a pre-compiled version of cryptography. However, after running `pyston -m pip install --upgrade pip` it showed that I was already using the latest version of pip, so not sure what's going on here! 

After installing rust with `sudo apt install rustc` pip was able to build cryptography from source and install it, but just so you know!

**Comment by kmod** [comment] 2021-05-23 01:25
Hi @calvma, thanks for the report! A copy of what you tried and what error you got would be helpful to understand what's happening.

My guess is that the error message is coming from the cryptography package, and that they provide pre-built packages for CPython which they are pointing you to. If they don't provide a pre-built package for Pyston then upgrading your pip won't help, you'll either need to build it from source or ask them to upload a package for Pyston.

**Comment by wamserma** [comment] 2021-05-24 19:53
cryptography is one of the [packages with C extensions](https://github.com/pyston/pyston/wiki#c-extensions) and recent versions of cryptography also build on Rust, so a Rust compiler must be present to rebuild it.
@calvma Build a wheel for cryptography on the machine with the Rust compiler, then you can use that wheel with pyston on other machines without Rust installed.

**Comment by SukiCZ** [comment] 2021-08-24 09:14
Hi, to append to this - the error when running `pip install cryptography` is

```
  ...
  creating build/temp.linux-x86_64-3.8-pyston2.3
  generating cffi module 'build/temp.linux-x86_64-3.8-pyston2.3/_openssl.c'
  running build_rust
  
      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation.html#rust
      5) If you are experiencing issues with Rust for *this release only* you may
         set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
      =============================DEBUG ASSISTANCE=============================
  
  error: can't find Rust compiler
  
  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
  
  To update pip, run:
  
      pip install --upgrade pip
  
  and then retry package installation.
  
  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
  
  This package requires Rust >=1.41.0.
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
```

As other mentioned you can:
* install Rust locally
* clone [cryptography](https://github.com/pyca/cryptography)
* checkout to stable branch e.g. `git checkout 3.4.7`
* build wheel using pyston `pyston setup.py bdist_wheel`
* copy `dist/cryptography-3.4.7-pyston38-pyston_23_x86_64_linux_gnu-linux_x86_64.whl` to a server
* install wheel on server using `pip install cryptography-3.4.7-pyston38-pyston_23_x86_64_linux_gnu-linux_x86_64.whl`

Hope it helps

**Comment by wamserma** [comment] 2021-08-24 19:36
@SukiCZ Thanks for adding instructions. Checking out the source of cryptography is not required, when pip is used to create the wheel, see https://pip.pypa.io/en/stable/cli/pip_wheel/
Another caveat: Cryptography links to OpenSSL, so one must ensure the machine used to build cryptography has the same OpenSSL version installed as the target machine.

**Comment by undingen** [comment] 2021-09-08 08:26
I'm closing this issue because it's not a bug in pyston as I have been able to install `cryptography` via:  
```
apt-get install libssl-dev libffi-dev rustc build-essential
pyston -m pip install cryptography
```
Right now installing many non python only packages is annoying because we don't provide prebuild wheels yet which means one has to manually install the source package dependencies :/ but this is something we want to improve over the coming months.

**Closed as completed by undingen** 2021-09-08 08:26 UTC
